//! # Database Models
//!
//! This file is auto-generated by `diesel_ext` based on the database schema.
//! It contains the struct definitions for all database tables, which are used
//! by Diesel as queryable models.
//!
//! **Do not edit this file manually.** Any changes will be overwritten the next
//! time the models are regenerated from the database.

// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use crate::schema::*;

use chrono::NaiveDateTime;
use diesel::prelude::*;
use uuid::Uuid;
#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = albums)]
pub struct Album {
    pub id: String,
    pub title: String,
    pub project_id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub artwork: Option<String>,
    pub description: Option<String>,
    pub links: Option<serde_json::Value>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = dates)]
pub struct Date {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub event_id: Option<String>,
    pub start_date: NaiveDateTime,
    pub end_date: NaiveDateTime,
    pub venue: String,
    pub city: String,
    pub state: Option<String>,
    pub country: String,
    pub ticket_url: Option<String>,
    pub venue_url: Option<String>,
    pub title: String,
    pub slug: String,
    pub content: String,
    pub project_id: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = email_campaigns)]
pub struct EmailCampaign {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub project_id: String,
    pub subject: String,
    pub content: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = email_deliveries)]
pub struct EmailDelivery {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub campaign_id: String,
    pub subscriber_id: String,
    pub status: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = events)]
pub struct Event {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = files)]
pub struct File {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub name: String,
    pub type_: String,
    pub size: i32,
    pub url: String,
    pub folder_id: String,
    pub project_id: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = folders)]
pub struct Folder {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub name: String,
    pub project_id: String,
    pub parent_id: Option<String>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = menu_item_labels)]
pub struct MenuItemLabel {
    pub id: String,
    pub menu_item_id: String,
    pub language: String,
    pub label: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = menu_items)]
pub struct MenuItem {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub menu_id: String,
    pub parent_id: Option<String>,
    pub type_: String,
    pub order: i32,
    pub page_id: Option<String>,
    pub submenu_id: Option<String>,
    pub url: Option<String>,
    pub active: i32,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = menus)]
pub struct Menu {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub name: String,
    pub description: Option<String>,
    pub active: i32,
    pub website_id: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = page_content)]
pub struct PageContent {
    pub id: Uuid,
    pub page_id: String,
    pub default_content: bool,
    pub preview: bool,
    pub language: String,
    pub content: serde_json::Value,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub template: Option<String>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = pages)]
pub struct Page {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub title: String,
    pub slug: String,
    pub type_: String,
    pub options: serde_json::Value,
    pub active: i32,
    pub home: bool,
    pub website_id: String,
    pub template: Option<String>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = payment_invoices)]
pub struct PaymentInvoice {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub subscription_id: String,
    pub stripe_invoice_id: String,
    pub amount_cents: i32,
    pub status: String,
    pub paid_at: Option<NaiveDateTime>,
    pub payment_intent_id: Option<String>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = payment_plans)]
pub struct PaymentPlan {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub name: String,
    pub description: Option<String>,
    pub base_price_cents: i32,
    pub per_site_price_cents: i32,
    pub promotional_code: Option<String>,
    pub promotional_discount_percent: Option<i32>,
    pub active: i32,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = payment_subscriptions)]
pub struct PaymentSubscription {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub project_id: String,
    pub plan_id: String,
    pub stripe_subscription_id: String,
    pub status: String,
    pub current_period_start: NaiveDateTime,
    pub current_period_end: NaiveDateTime,
    pub active_sites_count: i32,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = project_extras)]
pub struct ProjectExtra {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub project_id: String,
    pub extra: String,
    pub active: i32,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = project_promotions)]
pub struct ProjectPromotion {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub project_id: String,
    pub discount_percent: i32,
    pub start_date: NaiveDateTime,
    pub end_date: Option<NaiveDateTime>,
    pub description: Option<String>,
    pub active: i32,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = project_users)]
pub struct ProjectUser {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub user_id: String,
    pub project_id: String,
    pub role: String,
    pub terms_date: Option<NaiveDateTime>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = projects)]
pub struct Project {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub name: Option<String>,
    pub type_: String,
    pub active: i32,
    pub default_language: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = route_records)]
pub struct RouteRecord {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub domain: String,
    pub subdomain: Option<String>,
    pub website_id: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = stripe_customers)]
pub struct StripeCustomer {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub user_id: String,
    pub stripe_customer_id: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = subscribers)]
pub struct Subscriber {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub email: String,
    pub name: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub country: Option<String>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = subscriptions)]
pub struct Subscription {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub subscriber_id: String,
    pub project_id: String,
    pub subscription_method: Option<String>,
    pub unsubscribed_at: Option<NaiveDateTime>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(primary_key(role_name))]
#[diesel(table_name = user_roles)]
pub struct UserRole {
    pub role_name: String,
    pub value: i32,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = user_sessions)]
pub struct UserSession {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub expires_at: NaiveDateTime,
    pub user_id: String,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = users)]
pub struct User {
    pub id: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub email: String,
    pub password: String,
    pub name: Option<String>,
    pub role: String,
    pub terms_date: Option<NaiveDateTime>,
    pub confirmed_at: Option<NaiveDateTime>,
}

#[derive(
    Queryable, Selectable, Identifiable, Debug, Clone, serde::Serialize, serde::Deserialize,
)]
#[diesel(table_name = websites)]
pub struct Website {
    pub id: String,
    pub project_id: String,
    pub theme: String,
    pub theme_config: Option<serde_json::Value>,
    pub active: i32,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub title: String,
}
